package com.zzj.community.model;

public class UserMobile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.NAME
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.TOKEN
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.GMT_CREATE
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.BIO
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.AVATAR_URL
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mobile.PASSWORD
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.ID
     *
     * @return the value of user_mobile.ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.ID
     *
     * @param id the value for user_mobile.ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.ACCOUNT_ID
     *
     * @return the value of user_mobile.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.ACCOUNT_ID
     *
     * @param accountId the value for user_mobile.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.NAME
     *
     * @return the value of user_mobile.NAME
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.NAME
     *
     * @param name the value for user_mobile.NAME
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.TOKEN
     *
     * @return the value of user_mobile.TOKEN
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.TOKEN
     *
     * @param token the value for user_mobile.TOKEN
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.GMT_CREATE
     *
     * @return the value of user_mobile.GMT_CREATE
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.GMT_CREATE
     *
     * @param gmtCreate the value for user_mobile.GMT_CREATE
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.GMT_MODIFIED
     *
     * @return the value of user_mobile.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.GMT_MODIFIED
     *
     * @param gmtModified the value for user_mobile.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.BIO
     *
     * @return the value of user_mobile.BIO
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.BIO
     *
     * @param bio the value for user_mobile.BIO
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.AVATAR_URL
     *
     * @return the value of user_mobile.AVATAR_URL
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.AVATAR_URL
     *
     * @param avatarUrl the value for user_mobile.AVATAR_URL
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mobile.PASSWORD
     *
     * @return the value of user_mobile.PASSWORD
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mobile.PASSWORD
     *
     * @param password the value for user_mobile.PASSWORD
     *
     * @mbg.generated Fri Mar 13 12:53:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}